contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    #contact
    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
    path('contact/create/', views.create, name='create'),

    #user
    path('user/register/', views.register, name='register'),
    path('user/login/', views.login, name='login'),
    path('user/logout/', views.logout, name='logout'),
    path('user/update/', views.user_update, name='user_update'),

    #agenda
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name}'

class Contact(models.Model):
    first_name  = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=254, blank=True)
    created_data = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/') #adiciona a imagem na pasta media, cria uma pasta pictures e adiciona data na imagem
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from django import forms
from contact.models import Contact, Category
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import password_validation

class ContactForm(forms.ModelForm):

    picture = forms.ImageField(
        required=False,
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*'
            }
        )
    )

    new_category = forms.CharField(
        required=False,
        label='Create a new category',
        widget=forms.TextInput(attrs={
            'placeholder': 'Type a new category here if not in the list'
        })
    )

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'phone', 'email', 'description', 'category', 'new_category', 'picture')
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the first name. (Required)'
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the last name.'
                }
            ),
            'phone': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the phone number. format: (**) *****-****. (Required)'
                },
            ),
            'email': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the email.'
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'placeholder': 'Enter the description.'
                }
            )
        }

    def clean(self):
        cleaned_data = super().clean()
        new_category = cleaned_data.get('new_category')

        if new_category:
            category, created = Category.objects.get_or_create(name=new_category)
            cleaned_data['category'] = category

        return cleaned_data

class RegisterForm(UserCreationForm):

    first_name = forms.CharField(
        required=True
    )

    last_name = forms.CharField(
        required=True
    )

    email = forms.EmailField(
        required=True
    )
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the first name.'
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the last name.'
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the email.'
                }
            ),
            'username': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the username.'
                }
            )
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                forms.ValidationError('This e-mail already exists.')
            )
        
        return email
    
class UserUpdateForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the first name.'
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the last name.'
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the email.'
                }
            ),
            'username': forms.TextInput(
                attrs={
                    'placeholder': 'Enter the username.'
                }
            )
        }

    def save(self, commit=True):

        cleaned_data = self.cleaned_data
        user = super().save(commit=False)

        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user


    def clean_email(self):
        
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    forms.ValidationError('This e-mail already exists.')
            )
        
        return email
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except forms.ValidationError as errors:
                self.add_error(
                    'password1',
                    forms.ValidationError(errors)
                )
        
        return password1
    
    def clean(self):

        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    forms.ValidationError('Passwords must be the same')
                )

        return super().clean()

contact/views/contact_forms.py
from contact.forms import ContactForm
from contact.models import Contact

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required


@login_required(login_url='contact:login')
def create(request):

    form_action = reverse('contact:create')

    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            return redirect('contact:update', contact_id=contact.pk)


        return render(
            request,
            'contact/create.html',
            context
        )
    
    context = {
        'form': ContactForm(),
        'form_action': form_action
    }

    return render(
            request,
            'contact/create.html',
            context
    )


@login_required(login_url='contact:login')
def update(request, contact_id):

    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)

    form_action = reverse('contact:update', kwargs={'contact_id': contact_id})

    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES, instance=contact)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)
        
        return render(
            request,
            'contact/create.html',
            context
        )
    
    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action
    }

    return render(
            request,
            'contact/create.html',
            context
    )


@login_required(login_url='contact:login')
def delete(request, contact_id):

    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')
    
    context = {
        'contact': contact,
        'confirmation': confirmation
    }

    return render(
        request,
        'contact/contact.html',
        context
    )

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from contact.models import Contact
from django.contrib.auth.decorators import login_required

@login_required(login_url='contact:login')
def index(request):
    
    contacts = Contact.objects.filter(show=True, owner=request.user).order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
            'page_obj': page_obj,
            'site_title': 'Contatos - '
    } 

    return render(
        request,
        'contact/index.html',
        context
    )

def search(request):

    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects \
        .filter(show=True, owner=request.user) \
        .filter(
            Q(first_name__icontains=search_value) | 
            Q(last_name__icontains=search_value) | 
            Q(phone__icontains=search_value) | 
            Q(email__icontains=search_value) 
        ) \
        .order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - ',
        'search_value': search_value
    } 

    return render(
        request,
        'contact/index.html',
        context
    )

def contact(request, contact_id):

    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)

    context = {
        'contact': single_contact,
        'site_title': f'{single_contact.first_name} {single_contact.last_name} - '
    }

    return render(
        request,
        'contact/contact.html',
        context
    )

contact/views/user_forms.py
from django.shortcuts import redirect, render
from django.contrib import messages, auth
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

from contact.forms import RegisterForm, UserUpdateForm


def register(request):

    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'User Registered Successfully')
            return redirect('contact:login')

    context = {
        'form': form
    }

    return render(
        request,
        'contact/register.html',
        context
    )

def login(request):

    form = AuthenticationForm(request)

    if request.method == 'POST':

        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Login Successful')
            return redirect('contact:index')
        else:
            messages.error(request, 'Login invalid')

    context = {
        'form': form
    }

    return render(
        request,
        'contact/login.html',
        context
    )

@login_required(login_url='contact:login')
def user_update(request):

    form = UserUpdateForm(instance=request.user)

    if request.method == 'POST':

        form = UserUpdateForm(data=request.POST, instance=request.user)

        if form.is_valid():

            form.save()
            messages.success(request, 'Updated Successfully')
            return redirect('contact:user_update')
        else:
            messages.error(request, 'Update invalid')


    context = {
        'form': form
    }

    return render(
        request,
        'contact/user_update.html',
        context
    )

@login_required(login_url='contact:login')
def logout(request):
    
    auth.logout(request)

    return redirect('contact:login')

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.first_name}} {{contact.last_name}}
        </h1>

        <p><b>ID:</b> {{contact.id}} </p>
        <p><b>First Name:</b> {{contact.first_name}} </p>
        <p><b>Last Name:</b> {{contact.last_name}} </p>
        <p><b>Phone:</b> {{contact.phone}} </p>
        <p><b>Email:</b> {{contact.email}} </p>
        <p><b>Created at:</b> {{contact.created_data}} </p>
        <p><b>Description:</b> {{contact.description}} </p>
        <p><b>Category:</b> {{contact.category.name}} </p>

        {% if contact.picture %}
        <p>
            <img src="{{ contact.picture.url }}" alt="{{ contact.first_name }}  {{ contact.last_name }}">
        </p>
        {% endif %}

        {% if user == contact.owner %}
            <div class="contact-links">
                <a class="btn btn-link" href="{% url "contact:update" contact.id %}">Update</a>

                <form action="{% url "contact:delete" contact.id %}" method="POST">
                    {% csrf_token %}

                    {% if confirmation == 'no' %}
                        <button class="btn btn-link btn-delete" type="submit">Are you sure ?</button>
                        <input type="hidden" name="confirmation" value="yes">
                    {% else %}
                        <button class="btn btn-link btn-delete" type="submit">Delete</button>
                    {% endif %}
                </form>
            </div>
        {% endif %}
    </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">

        <h2>Contact</h2>
    
        <form 
        action="{{ form_action }}"
        method="POST"
        enctype="multipart/form-data"
        >

        {% csrf_token %}

        <div class="form-content">
            {% for field in form %}
                <div class="form-group">
                <label for="{{ field.id_label }}"> {{ field.label }}</label>
                {{ field }}
                {{ field.errors}}
                </div>

                {% if field.name == 'picture' and field.value.url%}
                    <div class="form-group">
                        <img src="{{field.value.url}}" alt="">
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        <div class="form-content">
            <div class="form-group">
            <button class="btn" type="submit">Send</button>
            </div>
        </div>

        </form>
    </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
    <div class="resposive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Contacts
            </caption>

            <thead>
                <tr class="table-row table-tow-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">First Name</th>
                    <th class="table-header">Last Name</th>
                    <th class="table-header">Phone</th>
                    <th class="table-header">E-mail</th>
                </tr>
            </thead>

            <tbody>
                {% for contact in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a 
                                class="table-link" 
                                href="{% url 'contact:contact' contact.id %}"
                            >
                                {{ contact.id }}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{ contact.first_name }}
                        </td>
                        <td class="table-cel">
                            {{ contact.last_name }}
                        </td>
                        <td class="table-cel">
                            {{ contact.phone }}
                        </td>
                        <td class="table-cel">
                            {{ contact.email }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
<div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum contato encontrado.
        </h1>

    </div>
{% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">

        <h2>Login</h2>
        
        {% include "contact/partials/_user_form.html" %}

    </div>
{% endblock content %}

contact/templates/contact/register.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">

        <h2>Register</h2>
    
        {% include "contact/partials/_user_form.html" %}
    </div>
{% endblock content %}

contact/templates/contact/user_update.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">

        <h2>Update User</h2>
    
        {% include "contact/partials/_user_form.html" %}
    </div>
{% endblock content %}